### PR TITLE
Add support for Kibana 5.5.0

### PR DESCRIPTION
**Pull request by fbaligand**
Fix issue #12

### CODE REVIEW

**Comment by fbaligand** [comment]
Hi @seadiaz,

I work on 5.5.0 compatibility this WE, because I'm very interested both by Kibana 5.5.0 and computed-columns plugin.
After some migration code essentially on Kibana core dependencies, computed-columns works great on my environment !

=> Could you please review my PR ?

**Comment by seadiaz** [comment]
Great!

I will review it ASAP


--
Sebastián Díaz
Skype: sebadiaz
seadiaz@gmail.com

**Comment by fbaligand** [comment]
Hi, 

Have you reviewed my PR ? 
For information, I made numerous tests with Kibana 5.5.0 and I'm currently using this version for my current professional project.

**Review by seadiaz — APPROVED** [review]

**Comment by seadiaz** [comment]
@fbaligand Sorry about my delay. I am catching up now.

😃

**Comment by fbaligand** [comment]
No soucy for the delay, thanks for the merge !
Happy to contribute to this great plugin !

**Pull request merged**
