### PR TITLE
Add string cols support

### PR DESCRIPTION
**Pull request by fbaligand**
Currently, computed-columns only consumes/produces number columns.

The goal of this PR is to provide :
- support to consume string cols
- support to produce string cols

### CODE REVIEW

**Comment by fbaligand** [comment]
What do you think if, for this PR, I use "Format" option to render strings using Mustache templating ?

**Review by seadiaz — APPROVED** [review]

**Comment by seadiaz** [comment]
@fbaligand Thanks again!

**Comment by fbaligand** [comment]
Thanks for the merge !

Could you publish a 0.7.0 release ?

Unless you wish I provide Mustache templating for string cols before ?

**Comment by seadiaz** [comment]
I thinks is better continuous release value, then I will release version 0.7.0 and then you add support for Mustache templating.

What do you think?


--
Sebastián Díaz
Skype: sebadiaz
seadiaz@gmail.com

**Comment by seadiaz** [comment]
After approved and merge your PR I was thinking about the feature and I don't understand why to support string as a source or destination. What kind of problem are you trying to solve?

**Comment by fbaligand** [comment]
It is useful, for instance, for such expressions :
`col[0] == "special-value" ? col[1] : col[2]`

**Pull request merged**
